version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  target-branch: dev
  commit-message:
    prefix: "[Dependabot]"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 99
