.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:IPXACT-github| image:: https://img.shields.io/badge/pyEDAA-IPXACT-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT
.. |SHIELD:png:IPXACT-github| image:: https://raster.shields.io/badge/pyEDAA-IPXACT-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT

.. # Sourcecode license
.. |SHIELD:svg:IPXACT-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: License.html
.. |SHIELD:png:IPXACT-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:IPXACT-tag| image:: https://img.shields.io/github/v/tag/edaa-org/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT/tags
.. |SHIELD:png:IPXACT-tag| image:: https://raster.shields.io/github/v/tag/edaa-org/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT/tags

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:IPXACT-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT/network/dependents
.. |SHIELD:png:IPXACT-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:IPXACT-gha-test| image:: https://img.shields.io/github/actions/workflow/status/edaa-org/pyEDAA.IPXACT/Pipeline.yml?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT/actions/workflows/Pipeline.yml
.. |SHIELD:png:IPXACT-gha-test| image:: https://raster.shields.io/github/actions/workflow/status/edaa-org/pyEDAA.IPXACT/Pipeline.yml?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:IPXACT-codacy-quality| image:: https://img.shields.io/codacy/grade/c924eeffd4cc49ed9ebbbe3a89b6fa76?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.IPXACT
.. |SHIELD:png:IPXACT-codacy-quality| image:: https://raster.shields.io/codacy/grade/c924eeffd4cc49ed9ebbbe3a89b6fa76?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.IPXACT

.. # Codacy - coverage
.. |SHIELD:svg:IPXACT-codacy-coverage| image:: https://img.shields.io/codacy/coverage/c924eeffd4cc49ed9ebbbe3a89b6fa76?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.IPXACT
.. |SHIELD:png:IPXACT-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/c924eeffd4cc49ed9ebbbe3a89b6fa76?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.IPXACT

.. # Codecov - coverage
.. |SHIELD:svg:IPXACT-codecov-coverage| image:: https://img.shields.io/codecov/c/github/edaa-org/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.IPXACT
.. |SHIELD:png:IPXACT-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/edaa-org/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.IPXACT

.. # Libraries - source rank
.. |SHIELD:svg:IPXACT-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.IPXACT/sourcerank
.. |SHIELD:png:IPXACT-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.IPXACT/sourcerank

.. # PyPI tag
.. |SHIELD:svg:IPXACT-pypi-tag| image:: https://img.shields.io/pypi/v/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.IPXACT/
.. |SHIELD:png:IPXACT-pypi-tag| image:: https://raster.shields.io/pypi/v/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.IPXACT/

.. # PyPI project status
.. |SHIELD:svg:IPXACT-pypi-status| image:: https://img.shields.io/pypi/status/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:IPXACT-pypi-status| image:: https://raster.shields.io/pypi/status/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:IPXACT-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:IPXACT-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:IPXACT-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.IPXACT
.. |SHIELD:png:IPXACT-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyEDAA.IPXACT?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.IPXACT

.. # Requires - status
.. |SHIELD:svg:IPXACT-req-status| image:: https://img.shields.io/requires/github/edaa-org/pyEDAA.IPXACT?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.IPXACT/requirements/?branch=main
.. |SHIELD:png:IPXACT-req-status| image:: https://raster.shields.io/requires/github/edaa-org/pyEDAA.IPXACT?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.IPXACT/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:IPXACT-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:IPXACT-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.IPXACT/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:IPXACT-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.IPXACT&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.IPXACT%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.IPXACT/
.. |SHIELD:png:IPXACT-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.IPXACT&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.IPXACT%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.IPXACT/

.. # Gitter
.. |SHIELD:svg:IPXACT-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:IPXACT-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
