name: Pipeline

on:
  push:
  workflow_dispatch:
  schedule:
# Every Friday at 22:00 - rerun pipeline to check for dependency-based issues
    - cron: '0 22 * * 5'

jobs:
  Pipeline:
    uses: pyTooling/Actions/.github/workflows/CompletePipeline.yml@r6
    with:
      package_namespace: 'pyEDAA'
      package_name:      'IPXACT'
      unittest_python_version_list: '3.11 3.12 3.13 3.14 pypy-3.11'
      bandit:            'true'
      pylint:            'false'
      codecov:           'true'
      codacy:            'true'
      dorny:             'true'
      cleanup:           'false'
    secrets:
      PYPI_TOKEN:    ${{ secrets.PYPI_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      CODACY_TOKEN:  ${{ secrets.CODACY_TOKEN }}
