name: Pipeline

on:
  push:
  workflow_dispatch:
  schedule:
# Every Friday at 22:00 - rerun pipeline to check for dependency-based issues
    - cron: '0 22 * * 5'

jobs:
  Pipeline:
    uses: pyTooling/Actions/.github/workflows/CompletePipeline.yml@dev
    with:
      package_namespace: pyEDAA
      package_name:      IPXACT
      codecov:           true
      codacy:            true
      dorny:             true
    secrets: inherit
